language: node_js
node_js:
  - 'node'
  - '10'
  - '8'
os:
  - windows
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm i --silent -g windows-build-tools; fi
after_success:
  - 'npm run coveralls'